### ISSUE TITLE
Use with Angular 2.3.x

### ISSUE THREAD

**Issue by jmpmscorp** [auth0/angular2-jwt#247]
New Angular 2.3.x versions use RxJS 5.0.0.rc4. If I upgrade my app to this versions, angular2-jwt has an unmeet dependency - RxJS 5.0.0.beta12.

Is there a way to upgrade both libraries?

Thanks.

**Comment by chenkie** [comment]
Fixed and releasing shortly.

**Comment by escardin** [comment]
@chenkie we should just update to 2.4 and the released version of rxjs

**Comment by ashleymorris2** [comment]
Is there an update on this? Still get the same issue.

**Comment by naveenkumarreddy** [comment]
I am also getting the same issue with Angular 2.3.x  use RxJS 5.0.0.rc4 but angular2-jwt has an unmeet dependency - RxJS 5.0.0.beta12. I think we need to update the package.json to include the major version of RxJs(^5.0.0-beat.12 instead ~5.0.0-beta.12)

**Comment by critchie** [comment]
Would like the release that fixes this as well.  The NPM warnings are getting a little old.  :-)

**Comment by amihailes** [comment]
Hi,

npm 4.0.5/ node 6.9.4

The warning npm is always:

npm WARN angular2-jwt@0.1.27 requires a peer of rxjs@5.0.0-beta.12 but none was installed.

**Comment by webplease** [comment]
same problem here.

**Comment by amihailes** [comment]
Is it about the version of Angular 2?

I use the 2.4.2 version actually.

**Comment by critchie** [comment]
In my case I'm using angular-cli@1.0.0-beta.24 and it creates apps using rxjs@5.0.1 and the angular2-jwt depends on the rxjs beta 12. angular2-jwt just needs to update to the latest angular and rxjs, verify and release.

**Comment by webplease** [comment]
solved with:

npm install Fank/angular2-jwt

**Comment by amihailes** [comment]
I think a new release is the good solution.

**Comment by escardin** [comment]
This should be resolved in 0.1.28. Please reopen if that is not the case.

**Comment by rjdjohnston** [comment]
This isn't solved. Same error.
`├── angular2-jwt@0.1.28  extraneous
└── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

npm WARN angular2-jwt@0.1.28 requires a peer of rxjs@^5.0.0 but none was installed.`

**Comment by escardin** [comment]
Upgrade to a newer 2.3.x release or go to 2.4.x
